---
- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
- name: remount proc
  ansible.posix.mount:
    path: /proc
    state: remounted
- name: restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
